"""addedmoreprefs

Revision ID: 02c1475c29ba
Revises: 17d7372285ac
Create Date: 2025-05-03 22:09:42.750610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c1475c29ba'
down_revision = '17d7372285ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_sign', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mbti_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smoking', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('drinking', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('music_preferences', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fitness', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pets', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('children', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('looking_for', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('looking_for')
        batch_op.drop_column('children')
        batch_op.drop_column('pets')
        batch_op.drop_column('education')
        batch_op.drop_column('job_title')
        batch_op.drop_column('fitness')
        batch_op.drop_column('music_preferences')
        batch_op.drop_column('drinking')
        batch_op.drop_column('smoking')
        batch_op.drop_column('height')
        batch_op.drop_column('religion')
        batch_op.drop_column('mbti_type')
        batch_op.drop_column('star_sign')

    # ### end Alembic commands ###
