"""images

Revision ID: dd0653787ecf
Revises: 1bdd58f333fd
Create Date: 2025-05-10 03:51:38.281570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0653787ecf'
down_revision = '1bdd58f333fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image5')
        batch_op.drop_column('image3')
        batch_op.drop_column('image1')
        batch_op.drop_column('image4')
        batch_op.drop_column('image2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('image1', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
