"""reset

Revision ID: f38390341273
Revises: 31f87ab0b80d
Create Date: 2025-05-10 02:47:46.691322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38390341273'
down_revision = '31f87ab0b80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('radius_km',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('looking_for')
        batch_op.drop_column('job_title')
        batch_op.drop_column('fitness')
        batch_op.drop_column('star_sign')
        batch_op.drop_column('mbti_type')
        batch_op.drop_column('children')
        batch_op.drop_column('religion')
        batch_op.drop_column('pets')
        batch_op.drop_column('smoking')
        batch_op.drop_column('education')
        batch_op.drop_column('drinking')
        batch_op.drop_column('height')
        batch_op.drop_column('music_preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_preferences', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('drinking', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('education', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('smoking', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('pets', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('children', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('mbti_type', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('star_sign', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fitness', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('looking_for', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('radius_km',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
